evologics_modem:
  modem_config:
    # Connection can be TCP/IP or SERIAL
    connection_type: 'TCP/IP'
    tcp_config:
      ip: 192.168.0.137
      port: 9200
    serial_config:
      baudrate: 19200
    hasAHRS: false
    source_level: 3
    local_address: 1
